// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dataflow_dataflow_in_loop_VITIS_LOOP_112_1 (
        ap_clk,
        ap_rst,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        channel_i,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        output_r,
        output_r_ap_vld,
        ap_start,
        channel_i_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [7:0] m_axi_gmem0_WDATA;
output  [0:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [7:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [10:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [2:0] channel_i;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [7:0] m_axi_gmem2_WDATA;
output  [0:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [7:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [10:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [63:0] m_axi_gmem1_WDATA;
output  [7:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [63:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] output_r;
input   output_r_ap_vld;
input   ap_start;
input   channel_i_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [7:0] input_buf_i_q0;
wire   [7:0] input_buf_t_q0;
wire   [7:0] input_buf_1_i_q0;
wire   [7:0] input_buf_1_t_q0;
wire   [7:0] weight_buf_i_q0;
wire   [7:0] weight_buf_t_q0;
wire   [7:0] weight_buf_1_i_q0;
wire   [7:0] weight_buf_1_t_q0;
wire   [31:0] output_buf_i_q0;
wire   [31:0] output_buf_t_q0;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire   [63:0] entry_proc_U0_output_r_c_din;
wire    entry_proc_U0_output_r_c_write;
wire    readDram_U0_ap_start;
wire    readDram_U0_ap_done;
wire    readDram_U0_ap_continue;
wire    readDram_U0_ap_idle;
wire    readDram_U0_ap_ready;
wire    readDram_U0_m_axi_gmem0_AWVALID;
wire   [63:0] readDram_U0_m_axi_gmem0_AWADDR;
wire   [0:0] readDram_U0_m_axi_gmem0_AWID;
wire   [31:0] readDram_U0_m_axi_gmem0_AWLEN;
wire   [2:0] readDram_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] readDram_U0_m_axi_gmem0_AWBURST;
wire   [1:0] readDram_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] readDram_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] readDram_U0_m_axi_gmem0_AWPROT;
wire   [3:0] readDram_U0_m_axi_gmem0_AWQOS;
wire   [3:0] readDram_U0_m_axi_gmem0_AWREGION;
wire   [0:0] readDram_U0_m_axi_gmem0_AWUSER;
wire    readDram_U0_m_axi_gmem0_WVALID;
wire   [7:0] readDram_U0_m_axi_gmem0_WDATA;
wire   [0:0] readDram_U0_m_axi_gmem0_WSTRB;
wire    readDram_U0_m_axi_gmem0_WLAST;
wire   [0:0] readDram_U0_m_axi_gmem0_WID;
wire   [0:0] readDram_U0_m_axi_gmem0_WUSER;
wire    readDram_U0_m_axi_gmem0_ARVALID;
wire   [63:0] readDram_U0_m_axi_gmem0_ARADDR;
wire   [0:0] readDram_U0_m_axi_gmem0_ARID;
wire   [31:0] readDram_U0_m_axi_gmem0_ARLEN;
wire   [2:0] readDram_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] readDram_U0_m_axi_gmem0_ARBURST;
wire   [1:0] readDram_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] readDram_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] readDram_U0_m_axi_gmem0_ARPROT;
wire   [3:0] readDram_U0_m_axi_gmem0_ARQOS;
wire   [3:0] readDram_U0_m_axi_gmem0_ARREGION;
wire   [0:0] readDram_U0_m_axi_gmem0_ARUSER;
wire    readDram_U0_m_axi_gmem0_RREADY;
wire    readDram_U0_m_axi_gmem0_BREADY;
wire   [2:0] readDram_U0_input_buf_address0;
wire    readDram_U0_input_buf_ce0;
wire    readDram_U0_input_buf_we0;
wire   [7:0] readDram_U0_input_buf_d0;
wire   [2:0] readDram_U0_input_buf_1_address0;
wire    readDram_U0_input_buf_1_ce0;
wire    readDram_U0_input_buf_1_we0;
wire   [7:0] readDram_U0_input_buf_1_d0;
wire   [1:0] readDram_U0_channel_i;
wire   [1:0] readDram_U0_ap_return;
wire    ap_channel_done_tmp;
wire    tmp_full_n;
reg    ap_sync_reg_channel_write_tmp;
wire    ap_sync_channel_write_tmp;
wire    ap_channel_done_input_buf_1;
wire    readDram_U0_input_buf_1_full_n;
reg    ap_sync_reg_channel_write_input_buf_1;
wire    ap_sync_channel_write_input_buf_1;
wire    ap_channel_done_input_buf;
wire    readDram_U0_input_buf_full_n;
reg    ap_sync_reg_channel_write_input_buf;
wire    ap_sync_channel_write_input_buf;
wire    weightDram_U0_ap_start;
wire    weightDram_U0_ap_done;
wire    weightDram_U0_ap_continue;
wire    weightDram_U0_ap_idle;
wire    weightDram_U0_ap_ready;
wire    weightDram_U0_m_axi_gmem2_AWVALID;
wire   [63:0] weightDram_U0_m_axi_gmem2_AWADDR;
wire   [0:0] weightDram_U0_m_axi_gmem2_AWID;
wire   [31:0] weightDram_U0_m_axi_gmem2_AWLEN;
wire   [2:0] weightDram_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] weightDram_U0_m_axi_gmem2_AWBURST;
wire   [1:0] weightDram_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] weightDram_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] weightDram_U0_m_axi_gmem2_AWPROT;
wire   [3:0] weightDram_U0_m_axi_gmem2_AWQOS;
wire   [3:0] weightDram_U0_m_axi_gmem2_AWREGION;
wire   [0:0] weightDram_U0_m_axi_gmem2_AWUSER;
wire    weightDram_U0_m_axi_gmem2_WVALID;
wire   [7:0] weightDram_U0_m_axi_gmem2_WDATA;
wire   [0:0] weightDram_U0_m_axi_gmem2_WSTRB;
wire    weightDram_U0_m_axi_gmem2_WLAST;
wire   [0:0] weightDram_U0_m_axi_gmem2_WID;
wire   [0:0] weightDram_U0_m_axi_gmem2_WUSER;
wire    weightDram_U0_m_axi_gmem2_ARVALID;
wire   [63:0] weightDram_U0_m_axi_gmem2_ARADDR;
wire   [0:0] weightDram_U0_m_axi_gmem2_ARID;
wire   [31:0] weightDram_U0_m_axi_gmem2_ARLEN;
wire   [2:0] weightDram_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] weightDram_U0_m_axi_gmem2_ARBURST;
wire   [1:0] weightDram_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] weightDram_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] weightDram_U0_m_axi_gmem2_ARPROT;
wire   [3:0] weightDram_U0_m_axi_gmem2_ARQOS;
wire   [3:0] weightDram_U0_m_axi_gmem2_ARREGION;
wire   [0:0] weightDram_U0_m_axi_gmem2_ARUSER;
wire    weightDram_U0_m_axi_gmem2_RREADY;
wire    weightDram_U0_m_axi_gmem2_BREADY;
wire   [2:0] weightDram_U0_weight_buf_address0;
wire    weightDram_U0_weight_buf_ce0;
wire    weightDram_U0_weight_buf_we0;
wire   [7:0] weightDram_U0_weight_buf_d0;
wire   [2:0] weightDram_U0_weight_buf_1_address0;
wire    weightDram_U0_weight_buf_1_ce0;
wire    weightDram_U0_weight_buf_1_we0;
wire   [7:0] weightDram_U0_weight_buf_1_d0;
wire   [1:0] weightDram_U0_channel_i;
wire    ap_channel_done_weight_buf_1;
wire    weightDram_U0_weight_buf_1_full_n;
reg    ap_sync_reg_channel_write_weight_buf_1;
wire    ap_sync_channel_write_weight_buf_1;
wire    ap_channel_done_weight_buf;
wire    weightDram_U0_weight_buf_full_n;
reg    ap_sync_reg_channel_write_weight_buf;
wire    ap_sync_channel_write_weight_buf;
wire    run_PE_U0_ap_start;
wire    run_PE_U0_ap_done;
wire    run_PE_U0_ap_continue;
wire    run_PE_U0_ap_idle;
wire    run_PE_U0_ap_ready;
wire   [2:0] run_PE_U0_input_buf1_address0;
wire    run_PE_U0_input_buf1_ce0;
wire   [2:0] run_PE_U0_input_buf_12_address0;
wire    run_PE_U0_input_buf_12_ce0;
wire   [2:0] run_PE_U0_weight_buf3_address0;
wire    run_PE_U0_weight_buf3_ce0;
wire   [2:0] run_PE_U0_weight_buf_14_address0;
wire    run_PE_U0_weight_buf_14_ce0;
wire   [1:0] run_PE_U0_output_buf5_address0;
wire    run_PE_U0_output_buf5_ce0;
wire    run_PE_U0_output_buf5_we0;
wire   [31:0] run_PE_U0_output_buf5_d0;
wire    writeDram_U0_ap_start;
wire    writeDram_U0_ap_done;
wire    writeDram_U0_ap_continue;
wire    writeDram_U0_ap_idle;
wire    writeDram_U0_ap_ready;
wire   [1:0] writeDram_U0_output_buf_address0;
wire    writeDram_U0_output_buf_ce0;
wire    writeDram_U0_m_axi_gmem1_AWVALID;
wire   [63:0] writeDram_U0_m_axi_gmem1_AWADDR;
wire   [0:0] writeDram_U0_m_axi_gmem1_AWID;
wire   [31:0] writeDram_U0_m_axi_gmem1_AWLEN;
wire   [2:0] writeDram_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] writeDram_U0_m_axi_gmem1_AWBURST;
wire   [1:0] writeDram_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] writeDram_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] writeDram_U0_m_axi_gmem1_AWPROT;
wire   [3:0] writeDram_U0_m_axi_gmem1_AWQOS;
wire   [3:0] writeDram_U0_m_axi_gmem1_AWREGION;
wire   [0:0] writeDram_U0_m_axi_gmem1_AWUSER;
wire    writeDram_U0_m_axi_gmem1_WVALID;
wire   [63:0] writeDram_U0_m_axi_gmem1_WDATA;
wire   [7:0] writeDram_U0_m_axi_gmem1_WSTRB;
wire    writeDram_U0_m_axi_gmem1_WLAST;
wire   [0:0] writeDram_U0_m_axi_gmem1_WID;
wire   [0:0] writeDram_U0_m_axi_gmem1_WUSER;
wire    writeDram_U0_m_axi_gmem1_ARVALID;
wire   [63:0] writeDram_U0_m_axi_gmem1_ARADDR;
wire   [0:0] writeDram_U0_m_axi_gmem1_ARID;
wire   [31:0] writeDram_U0_m_axi_gmem1_ARLEN;
wire   [2:0] writeDram_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] writeDram_U0_m_axi_gmem1_ARBURST;
wire   [1:0] writeDram_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] writeDram_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] writeDram_U0_m_axi_gmem1_ARPROT;
wire   [3:0] writeDram_U0_m_axi_gmem1_ARQOS;
wire   [3:0] writeDram_U0_m_axi_gmem1_ARREGION;
wire   [0:0] writeDram_U0_m_axi_gmem1_ARUSER;
wire    writeDram_U0_m_axi_gmem1_RREADY;
wire    writeDram_U0_m_axi_gmem1_BREADY;
wire    writeDram_U0_output_r_read;
wire    input_buf_i_full_n;
wire    input_buf_t_empty_n;
wire    input_buf_1_i_full_n;
wire    input_buf_1_t_empty_n;
wire    weight_buf_i_full_n;
wire    weight_buf_t_empty_n;
wire    weight_buf_1_i_full_n;
wire    weight_buf_1_t_empty_n;
wire    output_buf_i_full_n;
wire    output_buf_t_empty_n;
wire    output_r_c_full_n;
wire   [63:0] output_r_c_dout;
wire   [2:0] output_r_c_num_data_valid;
wire   [2:0] output_r_c_fifo_cap;
wire    output_r_c_empty_n;
wire   [1:0] tmp_dout;
wire   [1:0] tmp_num_data_valid;
wire   [1:0] tmp_fifo_cap;
wire    tmp_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_readDram_U0_ap_ready;
wire    ap_sync_readDram_U0_ap_ready;
reg    ap_sync_reg_weightDram_U0_ap_ready;
wire    ap_sync_weightDram_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_tmp = 1'b0;
#0 ap_sync_reg_channel_write_input_buf_1 = 1'b0;
#0 ap_sync_reg_channel_write_input_buf = 1'b0;
#0 ap_sync_reg_channel_write_weight_buf_1 = 1'b0;
#0 ap_sync_reg_channel_write_weight_buf = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_readDram_U0_ap_ready = 1'b0;
#0 ap_sync_reg_weightDram_U0_ap_ready = 1'b0;
end

dataflow_dataflow_in_loop_VITIS_LOOP_112_1_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
input_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(readDram_U0_input_buf_address0),
    .i_ce0(readDram_U0_input_buf_ce0),
    .i_we0(readDram_U0_input_buf_we0),
    .i_d0(readDram_U0_input_buf_d0),
    .i_q0(input_buf_i_q0),
    .t_address0(run_PE_U0_input_buf1_address0),
    .t_ce0(run_PE_U0_input_buf1_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(input_buf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(input_buf_i_full_n),
    .i_write(ap_channel_done_input_buf),
    .t_empty_n(input_buf_t_empty_n),
    .t_read(run_PE_U0_ap_ready)
);

dataflow_dataflow_in_loop_VITIS_LOOP_112_1_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
input_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(readDram_U0_input_buf_1_address0),
    .i_ce0(readDram_U0_input_buf_1_ce0),
    .i_we0(readDram_U0_input_buf_1_we0),
    .i_d0(readDram_U0_input_buf_1_d0),
    .i_q0(input_buf_1_i_q0),
    .t_address0(run_PE_U0_input_buf_12_address0),
    .t_ce0(run_PE_U0_input_buf_12_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(input_buf_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(input_buf_1_i_full_n),
    .i_write(ap_channel_done_input_buf_1),
    .t_empty_n(input_buf_1_t_empty_n),
    .t_read(run_PE_U0_ap_ready)
);

dataflow_dataflow_in_loop_VITIS_LOOP_112_1_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
weight_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(weightDram_U0_weight_buf_address0),
    .i_ce0(weightDram_U0_weight_buf_ce0),
    .i_we0(weightDram_U0_weight_buf_we0),
    .i_d0(weightDram_U0_weight_buf_d0),
    .i_q0(weight_buf_i_q0),
    .t_address0(run_PE_U0_weight_buf3_address0),
    .t_ce0(run_PE_U0_weight_buf3_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(weight_buf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(weight_buf_i_full_n),
    .i_write(ap_channel_done_weight_buf),
    .t_empty_n(weight_buf_t_empty_n),
    .t_read(run_PE_U0_ap_ready)
);

dataflow_dataflow_in_loop_VITIS_LOOP_112_1_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
weight_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(weightDram_U0_weight_buf_1_address0),
    .i_ce0(weightDram_U0_weight_buf_1_ce0),
    .i_we0(weightDram_U0_weight_buf_1_we0),
    .i_d0(weightDram_U0_weight_buf_1_d0),
    .i_q0(weight_buf_1_i_q0),
    .t_address0(run_PE_U0_weight_buf_14_address0),
    .t_ce0(run_PE_U0_weight_buf_14_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(weight_buf_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(weight_buf_1_i_full_n),
    .i_write(ap_channel_done_weight_buf_1),
    .t_empty_n(weight_buf_1_t_empty_n),
    .t_read(run_PE_U0_ap_ready)
);

dataflow_dataflow_in_loop_VITIS_LOOP_112_1_output_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
output_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(run_PE_U0_output_buf5_address0),
    .i_ce0(run_PE_U0_output_buf5_ce0),
    .i_we0(run_PE_U0_output_buf5_we0),
    .i_d0(run_PE_U0_output_buf5_d0),
    .i_q0(output_buf_i_q0),
    .t_address0(writeDram_U0_output_buf_address0),
    .t_ce0(writeDram_U0_output_buf_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(output_buf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(output_buf_i_full_n),
    .i_write(run_PE_U0_ap_done),
    .t_empty_n(output_buf_t_empty_n),
    .t_read(writeDram_U0_ap_ready)
);

dataflow_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .output_r(output_r),
    .output_r_c_din(entry_proc_U0_output_r_c_din),
    .output_r_c_num_data_valid(output_r_c_num_data_valid),
    .output_r_c_fifo_cap(output_r_c_fifo_cap),
    .output_r_c_full_n(output_r_c_full_n),
    .output_r_c_write(entry_proc_U0_output_r_c_write)
);

dataflow_readDram readDram_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(readDram_U0_ap_start),
    .ap_done(readDram_U0_ap_done),
    .ap_continue(readDram_U0_ap_continue),
    .ap_idle(readDram_U0_ap_idle),
    .ap_ready(readDram_U0_ap_ready),
    .m_axi_gmem0_AWVALID(readDram_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(readDram_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(readDram_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(readDram_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(readDram_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(readDram_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(readDram_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(readDram_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(readDram_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(readDram_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(readDram_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(readDram_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(readDram_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(readDram_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(readDram_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(readDram_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(readDram_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(readDram_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(readDram_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(readDram_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(readDram_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(readDram_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(readDram_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(readDram_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(readDram_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(readDram_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(readDram_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(readDram_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(readDram_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(readDram_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(readDram_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(readDram_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .input_buf_address0(readDram_U0_input_buf_address0),
    .input_buf_ce0(readDram_U0_input_buf_ce0),
    .input_buf_we0(readDram_U0_input_buf_we0),
    .input_buf_d0(readDram_U0_input_buf_d0),
    .input_buf_1_address0(readDram_U0_input_buf_1_address0),
    .input_buf_1_ce0(readDram_U0_input_buf_1_ce0),
    .input_buf_1_we0(readDram_U0_input_buf_1_we0),
    .input_buf_1_d0(readDram_U0_input_buf_1_d0),
    .channel_i(readDram_U0_channel_i),
    .ap_return(readDram_U0_ap_return)
);

dataflow_weightDram weightDram_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(weightDram_U0_ap_start),
    .ap_done(weightDram_U0_ap_done),
    .ap_continue(weightDram_U0_ap_continue),
    .ap_idle(weightDram_U0_ap_idle),
    .ap_ready(weightDram_U0_ap_ready),
    .m_axi_gmem2_AWVALID(weightDram_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(1'b0),
    .m_axi_gmem2_AWADDR(weightDram_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(weightDram_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(weightDram_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(weightDram_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(weightDram_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(weightDram_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(weightDram_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(weightDram_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(weightDram_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(weightDram_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(weightDram_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(weightDram_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(1'b0),
    .m_axi_gmem2_WDATA(weightDram_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(weightDram_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(weightDram_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(weightDram_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(weightDram_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(weightDram_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(m_axi_gmem2_ARREADY),
    .m_axi_gmem2_ARADDR(weightDram_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(weightDram_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(weightDram_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(weightDram_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(weightDram_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(weightDram_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(weightDram_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(weightDram_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(weightDram_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(weightDram_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(weightDram_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(m_axi_gmem2_RVALID),
    .m_axi_gmem2_RREADY(weightDram_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(m_axi_gmem2_RDATA),
    .m_axi_gmem2_RLAST(m_axi_gmem2_RLAST),
    .m_axi_gmem2_RID(m_axi_gmem2_RID),
    .m_axi_gmem2_RFIFONUM(m_axi_gmem2_RFIFONUM),
    .m_axi_gmem2_RUSER(m_axi_gmem2_RUSER),
    .m_axi_gmem2_RRESP(m_axi_gmem2_RRESP),
    .m_axi_gmem2_BVALID(1'b0),
    .m_axi_gmem2_BREADY(weightDram_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(2'd0),
    .m_axi_gmem2_BID(1'd0),
    .m_axi_gmem2_BUSER(1'd0),
    .weight_buf_address0(weightDram_U0_weight_buf_address0),
    .weight_buf_ce0(weightDram_U0_weight_buf_ce0),
    .weight_buf_we0(weightDram_U0_weight_buf_we0),
    .weight_buf_d0(weightDram_U0_weight_buf_d0),
    .weight_buf_1_address0(weightDram_U0_weight_buf_1_address0),
    .weight_buf_1_ce0(weightDram_U0_weight_buf_1_ce0),
    .weight_buf_1_we0(weightDram_U0_weight_buf_1_we0),
    .weight_buf_1_d0(weightDram_U0_weight_buf_1_d0),
    .channel_i(weightDram_U0_channel_i)
);

dataflow_run_PE run_PE_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(run_PE_U0_ap_start),
    .ap_done(run_PE_U0_ap_done),
    .ap_continue(run_PE_U0_ap_continue),
    .ap_idle(run_PE_U0_ap_idle),
    .ap_ready(run_PE_U0_ap_ready),
    .input_buf1_address0(run_PE_U0_input_buf1_address0),
    .input_buf1_ce0(run_PE_U0_input_buf1_ce0),
    .input_buf1_q0(input_buf_t_q0),
    .input_buf_12_address0(run_PE_U0_input_buf_12_address0),
    .input_buf_12_ce0(run_PE_U0_input_buf_12_ce0),
    .input_buf_12_q0(input_buf_1_t_q0),
    .weight_buf3_address0(run_PE_U0_weight_buf3_address0),
    .weight_buf3_ce0(run_PE_U0_weight_buf3_ce0),
    .weight_buf3_q0(weight_buf_t_q0),
    .weight_buf_14_address0(run_PE_U0_weight_buf_14_address0),
    .weight_buf_14_ce0(run_PE_U0_weight_buf_14_ce0),
    .weight_buf_14_q0(weight_buf_1_t_q0),
    .output_buf5_address0(run_PE_U0_output_buf5_address0),
    .output_buf5_ce0(run_PE_U0_output_buf5_ce0),
    .output_buf5_we0(run_PE_U0_output_buf5_we0),
    .output_buf5_d0(run_PE_U0_output_buf5_d0),
    .p_read(tmp_dout)
);

dataflow_writeDram writeDram_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(writeDram_U0_ap_start),
    .ap_done(writeDram_U0_ap_done),
    .ap_continue(writeDram_U0_ap_continue),
    .ap_idle(writeDram_U0_ap_idle),
    .ap_ready(writeDram_U0_ap_ready),
    .output_buf_address0(writeDram_U0_output_buf_address0),
    .output_buf_ce0(writeDram_U0_output_buf_ce0),
    .output_buf_q0(output_buf_t_q0),
    .m_axi_gmem1_AWVALID(writeDram_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(m_axi_gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(writeDram_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(writeDram_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(writeDram_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(writeDram_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(writeDram_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(writeDram_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(writeDram_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(writeDram_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(writeDram_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(writeDram_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(writeDram_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(writeDram_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(m_axi_gmem1_WREADY),
    .m_axi_gmem1_WDATA(writeDram_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(writeDram_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(writeDram_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(writeDram_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(writeDram_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(writeDram_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(writeDram_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(writeDram_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(writeDram_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(writeDram_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(writeDram_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(writeDram_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(writeDram_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(writeDram_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(writeDram_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(writeDram_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(writeDram_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(writeDram_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(64'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(9'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(m_axi_gmem1_BVALID),
    .m_axi_gmem1_BREADY(writeDram_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(m_axi_gmem1_BRESP),
    .m_axi_gmem1_BID(m_axi_gmem1_BID),
    .m_axi_gmem1_BUSER(m_axi_gmem1_BUSER),
    .output_r_dout(output_r_c_dout),
    .output_r_num_data_valid(output_r_c_num_data_valid),
    .output_r_fifo_cap(output_r_c_fifo_cap),
    .output_r_empty_n(output_r_c_empty_n),
    .output_r_read(writeDram_U0_output_r_read)
);

dataflow_fifo_w64_d4_S output_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_output_r_c_din),
    .if_full_n(output_r_c_full_n),
    .if_write(entry_proc_U0_output_r_c_write),
    .if_dout(output_r_c_dout),
    .if_num_data_valid(output_r_c_num_data_valid),
    .if_fifo_cap(output_r_c_fifo_cap),
    .if_empty_n(output_r_c_empty_n),
    .if_read(writeDram_U0_output_r_read)
);

dataflow_fifo_w2_d2_S tmp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readDram_U0_ap_return),
    .if_full_n(tmp_full_n),
    .if_write(ap_channel_done_tmp),
    .if_dout(tmp_dout),
    .if_num_data_valid(tmp_num_data_valid),
    .if_fifo_cap(tmp_fifo_cap),
    .if_empty_n(tmp_empty_n),
    .if_read(run_PE_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_input_buf <= 1'b0;
    end else begin
        if (((readDram_U0_ap_done & readDram_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_input_buf <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_input_buf <= ap_sync_channel_write_input_buf;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_input_buf_1 <= 1'b0;
    end else begin
        if (((readDram_U0_ap_done & readDram_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_input_buf_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_input_buf_1 <= ap_sync_channel_write_input_buf_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_tmp <= 1'b0;
    end else begin
        if (((readDram_U0_ap_done & readDram_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_tmp <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_tmp <= ap_sync_channel_write_tmp;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_weight_buf <= 1'b0;
    end else begin
        if (((weightDram_U0_ap_done & weightDram_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_weight_buf <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_weight_buf <= ap_sync_channel_write_weight_buf;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_weight_buf_1 <= 1'b0;
    end else begin
        if (((weightDram_U0_ap_done & weightDram_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_weight_buf_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_weight_buf_1 <= ap_sync_channel_write_weight_buf_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_readDram_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_readDram_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_readDram_U0_ap_ready <= ap_sync_readDram_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_weightDram_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_weightDram_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_weightDram_U0_ap_ready <= ap_sync_weightDram_U0_ap_ready;
        end
    end
end

assign ap_channel_done_input_buf = (readDram_U0_ap_done & (ap_sync_reg_channel_write_input_buf ^ 1'b1));

assign ap_channel_done_input_buf_1 = (readDram_U0_ap_done & (ap_sync_reg_channel_write_input_buf_1 ^ 1'b1));

assign ap_channel_done_tmp = (readDram_U0_ap_done & (ap_sync_reg_channel_write_tmp ^ 1'b1));

assign ap_channel_done_weight_buf = (weightDram_U0_ap_done & (ap_sync_reg_channel_write_weight_buf ^ 1'b1));

assign ap_channel_done_weight_buf_1 = (weightDram_U0_ap_done & (ap_sync_reg_channel_write_weight_buf_1 ^ 1'b1));

assign ap_done = writeDram_U0_ap_done;

assign ap_idle = (writeDram_U0_ap_idle & weightDram_U0_ap_idle & run_PE_U0_ap_idle & readDram_U0_ap_idle & (tmp_empty_n ^ 1'b1) & (output_buf_t_empty_n ^ 1'b1) & (weight_buf_1_t_empty_n ^ 1'b1) & (weight_buf_t_empty_n ^ 1'b1) & (input_buf_1_t_empty_n ^ 1'b1) & (input_buf_t_empty_n ^ 1'b1) & entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_channel_write_input_buf = ((readDram_U0_input_buf_full_n & ap_channel_done_input_buf) | ap_sync_reg_channel_write_input_buf);

assign ap_sync_channel_write_input_buf_1 = ((readDram_U0_input_buf_1_full_n & ap_channel_done_input_buf_1) | ap_sync_reg_channel_write_input_buf_1);

assign ap_sync_channel_write_tmp = ((tmp_full_n & ap_channel_done_tmp) | ap_sync_reg_channel_write_tmp);

assign ap_sync_channel_write_weight_buf = ((weightDram_U0_weight_buf_full_n & ap_channel_done_weight_buf) | ap_sync_reg_channel_write_weight_buf);

assign ap_sync_channel_write_weight_buf_1 = ((weightDram_U0_weight_buf_1_full_n & ap_channel_done_weight_buf_1) | ap_sync_reg_channel_write_weight_buf_1);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_readDram_U0_ap_ready = (readDram_U0_ap_ready | ap_sync_reg_readDram_U0_ap_ready);

assign ap_sync_ready = (ap_sync_weightDram_U0_ap_ready & ap_sync_readDram_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign ap_sync_weightDram_U0_ap_ready = (weightDram_U0_ap_ready | ap_sync_reg_weightDram_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign m_axi_gmem0_ARADDR = readDram_U0_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = readDram_U0_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = readDram_U0_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = readDram_U0_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = readDram_U0_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = readDram_U0_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = readDram_U0_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = readDram_U0_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = readDram_U0_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = readDram_U0_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = readDram_U0_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_ARVALID = readDram_U0_m_axi_gmem0_ARVALID;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_RREADY = readDram_U0_m_axi_gmem0_RREADY;

assign m_axi_gmem0_WDATA = 8'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 1'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = writeDram_U0_m_axi_gmem1_AWADDR;

assign m_axi_gmem1_AWBURST = writeDram_U0_m_axi_gmem1_AWBURST;

assign m_axi_gmem1_AWCACHE = writeDram_U0_m_axi_gmem1_AWCACHE;

assign m_axi_gmem1_AWID = writeDram_U0_m_axi_gmem1_AWID;

assign m_axi_gmem1_AWLEN = writeDram_U0_m_axi_gmem1_AWLEN;

assign m_axi_gmem1_AWLOCK = writeDram_U0_m_axi_gmem1_AWLOCK;

assign m_axi_gmem1_AWPROT = writeDram_U0_m_axi_gmem1_AWPROT;

assign m_axi_gmem1_AWQOS = writeDram_U0_m_axi_gmem1_AWQOS;

assign m_axi_gmem1_AWREGION = writeDram_U0_m_axi_gmem1_AWREGION;

assign m_axi_gmem1_AWSIZE = writeDram_U0_m_axi_gmem1_AWSIZE;

assign m_axi_gmem1_AWUSER = writeDram_U0_m_axi_gmem1_AWUSER;

assign m_axi_gmem1_AWVALID = writeDram_U0_m_axi_gmem1_AWVALID;

assign m_axi_gmem1_BREADY = writeDram_U0_m_axi_gmem1_BREADY;

assign m_axi_gmem1_RREADY = 1'b0;

assign m_axi_gmem1_WDATA = writeDram_U0_m_axi_gmem1_WDATA;

assign m_axi_gmem1_WID = writeDram_U0_m_axi_gmem1_WID;

assign m_axi_gmem1_WLAST = writeDram_U0_m_axi_gmem1_WLAST;

assign m_axi_gmem1_WSTRB = writeDram_U0_m_axi_gmem1_WSTRB;

assign m_axi_gmem1_WUSER = writeDram_U0_m_axi_gmem1_WUSER;

assign m_axi_gmem1_WVALID = writeDram_U0_m_axi_gmem1_WVALID;

assign m_axi_gmem2_ARADDR = weightDram_U0_m_axi_gmem2_ARADDR;

assign m_axi_gmem2_ARBURST = weightDram_U0_m_axi_gmem2_ARBURST;

assign m_axi_gmem2_ARCACHE = weightDram_U0_m_axi_gmem2_ARCACHE;

assign m_axi_gmem2_ARID = weightDram_U0_m_axi_gmem2_ARID;

assign m_axi_gmem2_ARLEN = weightDram_U0_m_axi_gmem2_ARLEN;

assign m_axi_gmem2_ARLOCK = weightDram_U0_m_axi_gmem2_ARLOCK;

assign m_axi_gmem2_ARPROT = weightDram_U0_m_axi_gmem2_ARPROT;

assign m_axi_gmem2_ARQOS = weightDram_U0_m_axi_gmem2_ARQOS;

assign m_axi_gmem2_ARREGION = weightDram_U0_m_axi_gmem2_ARREGION;

assign m_axi_gmem2_ARSIZE = weightDram_U0_m_axi_gmem2_ARSIZE;

assign m_axi_gmem2_ARUSER = weightDram_U0_m_axi_gmem2_ARUSER;

assign m_axi_gmem2_ARVALID = weightDram_U0_m_axi_gmem2_ARVALID;

assign m_axi_gmem2_AWADDR = 64'd0;

assign m_axi_gmem2_AWBURST = 2'd0;

assign m_axi_gmem2_AWCACHE = 4'd0;

assign m_axi_gmem2_AWID = 1'd0;

assign m_axi_gmem2_AWLEN = 32'd0;

assign m_axi_gmem2_AWLOCK = 2'd0;

assign m_axi_gmem2_AWPROT = 3'd0;

assign m_axi_gmem2_AWQOS = 4'd0;

assign m_axi_gmem2_AWREGION = 4'd0;

assign m_axi_gmem2_AWSIZE = 3'd0;

assign m_axi_gmem2_AWUSER = 1'd0;

assign m_axi_gmem2_AWVALID = 1'b0;

assign m_axi_gmem2_BREADY = 1'b0;

assign m_axi_gmem2_RREADY = weightDram_U0_m_axi_gmem2_RREADY;

assign m_axi_gmem2_WDATA = 8'd0;

assign m_axi_gmem2_WID = 1'd0;

assign m_axi_gmem2_WLAST = 1'b0;

assign m_axi_gmem2_WSTRB = 1'd0;

assign m_axi_gmem2_WUSER = 1'd0;

assign m_axi_gmem2_WVALID = 1'b0;

assign readDram_U0_ap_continue = (ap_sync_channel_write_tmp & ap_sync_channel_write_input_buf_1 & ap_sync_channel_write_input_buf);

assign readDram_U0_ap_start = ((ap_sync_reg_readDram_U0_ap_ready ^ 1'b1) & ap_start);

assign readDram_U0_channel_i = {{channel_i[(2 - 3'd1):0]}};

assign readDram_U0_input_buf_1_full_n = input_buf_1_i_full_n;

assign readDram_U0_input_buf_full_n = input_buf_i_full_n;

assign run_PE_U0_ap_continue = output_buf_i_full_n;

assign run_PE_U0_ap_start = (weight_buf_t_empty_n & weight_buf_1_t_empty_n & tmp_empty_n & input_buf_t_empty_n & input_buf_1_t_empty_n);

assign weightDram_U0_ap_continue = (ap_sync_channel_write_weight_buf_1 & ap_sync_channel_write_weight_buf);

assign weightDram_U0_ap_start = ((ap_sync_reg_weightDram_U0_ap_ready ^ 1'b1) & ap_start);

assign weightDram_U0_channel_i = {{channel_i[(2 - 3'd1):0]}};

assign weightDram_U0_weight_buf_1_full_n = weight_buf_1_i_full_n;

assign weightDram_U0_weight_buf_full_n = weight_buf_i_full_n;

assign writeDram_U0_ap_continue = ap_continue;

assign writeDram_U0_ap_start = output_buf_t_empty_n;

endmodule //dataflow_dataflow_in_loop_VITIS_LOOP_112_1
