set_property PACKAGE_PIN D7 [get_ports clk_in]
set_property PACKAGE_PIN B6 [get_ports {led_out[3]}]
set_property PACKAGE_PIN C5 [get_ports {led_out[2]}]
set_property PACKAGE_PIN E8 [get_ports {led_out[1]}]
set_property PACKAGE_PIN D8 [get_ports {led_out[0]}]
set_property PACKAGE_PIN G5 [get_ports reset_n]
set_property PACKAGE_PIN F8 [get_ports sw_in]
set_property IOSTANDARD LVCMOS18 [get_ports {clk_in}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports reset_n]
set_property IOSTANDARD LVCMOS18 [get_ports sw_in]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sw_in]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_in]
#create_clock -period 5 [get_ports sw_in]